/**
 * VectisDocument — TypeScript high-level API wrapping the Wasm CRDT engine.
 *
 * Usage:
 *   const doc = await VectisDocument.create(actorId, 'wss://my-server/ws');
 *   const strokeId = doc.insertStroke(points, { tool: ToolKind.Pen, color: 0xFF0000FF, width: 2, opacity: 1 });
 *   doc.onStrokesChanged = (ids) => renderer.redraw(ids);
 */

// These are generated by wasm-pack from the Rust crate.
// Run: wasm-pack build --target web
import init, { WasmDocument } from '../pkg/vectis_crdt.js';

// ─── Types ───────────────────────────────────────────────────────────────────

export const enum ToolKind {
  Pen    = 0,
  Eraser = 1,
  Marker = 2,
  Laser  = 3,
  Shape  = 4,
  Arrow  = 5,
}

export interface StrokeOptions {
  tool?: ToolKind;
  /** 0xRRGGBBAA packed integer */
  color?: number;
  width?: number;
  opacity?: number;
}

/** Axis-Aligned Bounding Box in canvas coordinates (no padding). */
export interface Aabb {
  minX: number;
  minY: number;
  maxX: number;
  maxY: number;
}

export interface DocumentStats {
  total_items: number;
  visible: number;
  tombstones: number;
  tombstone_ratio: number;
  gc_gen: number;
  pending_ops: number;
}

export interface GcStats {
  removed: number;
  freed: number;
  gen: number;
  partial: boolean;
}

/** Transform2D: affine matrix [a, b, c, d, tx, ty] */
export type Transform2D = [number, number, number, number, number, number];

/** StrokeId: 16-byte Uint8Array (lamport u64 LE + actor u64 LE). */
export type StrokeId = Uint8Array;

/** Message type byte for the framing protocol. */
const enum MsgType {
  UPDATE       = 0x01,
  STATE_VECTOR = 0x02,
  SNAPSHOT     = 0x03,
  MVV          = 0x04,
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

function wrapMessage(type_: MsgType, payload: Uint8Array): Uint8Array {
  const out = new Uint8Array(1 + payload.length);
  out[0] = type_;
  out.set(payload, 1);
  return out;
}

function encodeU32LE(v: number): Uint8Array {
  const buf = new ArrayBuffer(4);
  new DataView(buf).setUint32(0, v, true);
  return new Uint8Array(buf);
}

function encodeF32LE(v: number): Uint8Array {
  const buf = new ArrayBuffer(4);
  new DataView(buf).setFloat32(0, v, true);
  return new Uint8Array(buf);
}

function encodeTransform(t: Transform2D): Uint8Array {
  const buf = new ArrayBuffer(24);
  const dv = new DataView(buf);
  t.forEach((v, i) => dv.setFloat32(i * 4, v, true));
  return new Uint8Array(buf);
}

/** Parse an array of StrokeIds (16 bytes each) from a flat Uint8Array. */
function parseStrokeIds(buf: Uint8Array): StrokeId[] {
  const ids: StrokeId[] = [];
  for (let i = 0; i + 16 <= buf.length; i += 16) {
    ids.push(buf.slice(i, i + 16));
  }
  return ids;
}

// ─── RenderStroke ─────────────────────────────────────────────────────────────

/** Parsed rendering data for one stroke. */
export interface RenderStroke {
  id: StrokeId;
  tool: ToolKind;
  color: number;
  width: number;
  opacity: number;
  transform: Transform2D;
  /** Float32Array view: [x0, y0, pressure0, x1, y1, pressure1, ...] */
  points: Float32Array;
}

/**
 * Parse the render data buffer built by `WasmDocument.build_render_data()`.
 *
 * Buffer layout per stroke (matches Rust wasm_bridge.rs):
 *   [id: 16B][point_count: u32 LE][tool: u8]
 *   [color: u32 LE][width: f32 LE][opacity: f32 LE]
 *   [transform: 6×f32 LE = 24B]
 *   [points: point_count × 3 × f32 LE]
 */
function parseRenderData(wasmMemory: WebAssembly.Memory, ptr: number, len: number): RenderStroke[] {
  const buf = new Uint8Array(wasmMemory.buffer, ptr, len);
  const dv = new DataView(wasmMemory.buffer, ptr, len);
  const strokes: RenderStroke[] = [];
  let offset = 0;

  while (offset < len) {
    if (offset + 16 + 4 + 1 + 4 + 4 + 4 + 24 > len) break;

    const id = buf.slice(offset, offset + 16);
    offset += 16;

    const pointCount = dv.getUint32(offset, true);
    offset += 4;

    const tool = buf[offset++] as ToolKind;
    const color = dv.getUint32(offset, true); offset += 4;
    const width = dv.getFloat32(offset, true); offset += 4;
    const opacity = dv.getFloat32(offset, true); offset += 4;

    const transform: Transform2D = [
      dv.getFloat32(offset, true), dv.getFloat32(offset + 4, true),
      dv.getFloat32(offset + 8, true), dv.getFloat32(offset + 12, true),
      dv.getFloat32(offset + 16, true), dv.getFloat32(offset + 20, true),
    ];
    offset += 24;

    const pointsByteLen = pointCount * 3 * 4;
    if (offset + pointsByteLen > len) break;

    // Zero-copy view into Wasm memory.
    const points = new Float32Array(wasmMemory.buffer, ptr + offset, pointCount * 3);
    offset += pointsByteLen;

    strokes.push({ id, tool, color, width, opacity, transform, points });
  }

  return strokes;
}

// ─── VectisDocument ───────────────────────────────────────────────────────────

export class VectisDocument {
  private wasm!: WasmDocument;
  private memory!: WebAssembly.Memory;
  private ws!: WebSocket;
  private pendingFlush: number | null = null;
  private connected = false;

  // ─── Callbacks ─────────────────────────────────────────────────────────────

  /** Called with the IDs of strokes that changed after a remote update. */
  onStrokesChanged?: (ids: StrokeId[]) => void;
  /** Called when the WebSocket connects or reconnects. */
  onConnected?: () => void;
  /** Called when the WebSocket disconnects. */
  onDisconnected?: () => void;

  // ─── Factory ───────────────────────────────────────────────────────────────

  static async create(actorId: bigint, wsUrl: string): Promise<VectisDocument> {
    const wasmModule = await init();
    const doc = new VectisDocument();
    doc.wasm = new WasmDocument(actorId);
    // WebAssembly.Memory is exposed on the module instance.
    doc.memory = (wasmModule as any).memory as WebAssembly.Memory;
    doc.connectWebSocket(wsUrl);
    return doc;
  }

  static async fromSnapshot(
    actorId: bigint,
    snapshot: Uint8Array,
    wsUrl: string,
  ): Promise<VectisDocument> {
    const wasmModule = await init();
    const doc = new VectisDocument();
    doc.wasm = WasmDocument.from_snapshot(actorId, snapshot);
    doc.memory = (wasmModule as any).memory as WebAssembly.Memory;
    doc.connectWebSocket(wsUrl);
    return doc;
  }

  // ─── Local Operations ──────────────────────────────────────────────────────

  /**
   * Insert a stroke.
   *
   * `points` layout: `[x0, y0, pressure0, x1, y1, pressure1, ...]`
   * Returns a 16-byte StrokeId.
   */
  insertStroke(points: Float32Array, opts: StrokeOptions = {}): StrokeId {
    const {
      tool = ToolKind.Pen,
      color = 0x000000FF,
      width = 2.0,
      opacity = 1.0,
    } = opts;
    const id = this.wasm.insert_stroke(points, tool, color >>> 0, width, opacity);
    this.scheduleFlush();
    return id;
  }

  /** Delete a stroke by ID. */
  deleteStroke(strokeId: StrokeId): boolean {
    const ok = this.wasm.delete_stroke(strokeId);
    if (ok) this.scheduleFlush();
    return ok;
  }

  /** Update the color of a stroke (0xRRGGBBAA). */
  updateStrokeColor(strokeId: StrokeId, color: number): void {
    this.wasm.update_stroke_property(strokeId, 0, encodeU32LE(color));
    this.scheduleFlush();
  }

  /** Update the width of a stroke. */
  updateStrokeWidth(strokeId: StrokeId, width: number): void {
    this.wasm.update_stroke_property(strokeId, 1, encodeF32LE(width));
    this.scheduleFlush();
  }

  /** Update the opacity of a stroke (0.0–1.0). */
  updateStrokeOpacity(strokeId: StrokeId, opacity: number): void {
    this.wasm.update_stroke_property(strokeId, 2, encodeF32LE(opacity));
    this.scheduleFlush();
  }

  /** Update the affine transform of a stroke. */
  updateStrokeTransform(strokeId: StrokeId, transform: Transform2D): void {
    this.wasm.update_stroke_property(strokeId, 3, encodeTransform(transform));
    this.scheduleFlush();
  }

  // ─── Rendering (Zero-Copy Hot Path) ────────────────────────────────────────

  /**
   * Build render data for ALL visible strokes and return parsed stroke objects.
   * The `points` arrays are zero-copy views into Wasm memory.
   *
   * For large canvases (> 1 000 strokes), prefer `getRenderDataViewport`.
   *
   * CAUTION: Any subsequent Wasm operation may invalidate the point views.
   * Consume/copy before calling any other method.
   */
  getRenderData(): RenderStroke[] {
    const ptr = this.wasm.build_render_data();
    const len = this.wasm.get_render_data_len();
    if (len === 0) return [];
    return parseRenderData(this.memory, ptr, len);
  }

  /**
   * Build render data for only the strokes visible within a canvas-space
   * viewport rectangle. Strokes entirely outside are culled without point
   * iteration — O(visible) instead of O(total).
   *
   * @param vx0 Left edge of the viewport in canvas coordinates.
   * @param vy0 Top edge.
   * @param vx1 Right edge.
   * @param vy1 Bottom edge.
   * @param strokeExpand Padding added to each stroke's bounds before the
   *   intersection test. Pass `maxStrokeWidth / 2` to avoid clipping thick
   *   strokes at viewport edges. Default: `32`.
   *
   * @example
   * // Camera panned to (camX, camY), viewport is (viewW × viewH):
   * const strokes = doc.getRenderDataViewport(camX, camY, camX + viewW, camY + viewH);
   */
  getRenderDataViewport(
    vx0: number,
    vy0: number,
    vx1: number,
    vy1: number,
    strokeExpand = 32,
  ): RenderStroke[] {
    const ptr = this.wasm.build_render_data_viewport(vx0, vy0, vx1, vy1, strokeExpand);
    const len = this.wasm.get_render_data_len();
    if (len === 0) return [];
    return parseRenderData(this.memory, ptr, len);
  }

  /**
   * Get a zero-copy Float32Array view of a specific stroke's points.
   * Layout: `[x, y, pressure, ...]`
   *
   * Returns null if the stroke doesn't exist.
   * CAUTION: invalidated by heap reallocation.
   */
  getStrokePointsView(strokeId: StrokeId): Float32Array | null {
    const ptr = this.wasm.get_stroke_points_ptr(strokeId);
    const count = this.wasm.get_stroke_point_count(strokeId);
    if (ptr === 0 || count === 0) return null;
    return new Float32Array(this.memory.buffer, ptr, count * 3);
  }

  /**
   * Get the bounding box of a stroke in canvas coordinates.
   * Returns null if the stroke doesn't exist.
   * Bounds are tight (no padding) — add `strokeWidth / 2` if needed.
   */
  getStrokeBounds(strokeId: StrokeId): Aabb | null {
    const raw = this.wasm.get_stroke_bounds(strokeId);
    if (raw.length < 16) return null;
    const dv = new DataView(raw.buffer, raw.byteOffset, 16);
    return {
      minX: dv.getFloat32(0, true),
      minY: dv.getFloat32(4, true),
      maxX: dv.getFloat32(8, true),
      maxY: dv.getFloat32(12, true),
    };
  }

  /** Returns all visible stroke IDs in z-order (bottom to top). */
  getVisibleStrokeIds(): StrokeId[] {
    return parseStrokeIds(this.wasm.get_visible_stroke_ids());
  }

  // ─── Simplification ────────────────────────────────────────────────────────

  /**
   * Set the RDP epsilon for automatic point simplification applied to every
   * new stroke on insert. `0` disables auto-simplification.
   * Default: `0.5` (sub-pixel accuracy at normal zoom on high-DPI displays).
   */
  setSimplifyEpsilon(epsilon: number): void {
    this.wasm.set_simplify_epsilon(epsilon);
  }

  /**
   * Manually simplify an existing stroke's points.
   * Useful to retroactively compress strokes loaded from a snapshot.
   * Returns the number of points removed.
   */
  simplifyStroke(strokeId: StrokeId, epsilon = 0.5): number {
    return this.wasm.simplify_stroke(strokeId, epsilon);
  }

  // ─── Undo ──────────────────────────────────────────────────────────────────

  /**
   * Undo the last stroke drawn by the local actor.
   *
   * Emits a `DeleteStroke` CRDT operation — visible to all peers.
   * If the stroke was already deleted remotely, silently skips to the
   * previous one.
   *
   * Returns the deleted StrokeId, or null if nothing to undo.
   * The delete op is queued and flushed on the next rAF.
   */
  undo(): StrokeId | null {
    const raw = this.wasm.undo();
    if (raw.length === 0) return null;
    this.scheduleFlush();
    return raw as StrokeId;
  }

  /** Number of strokes available to undo (local actor only). */
  get undoDepth(): number {
    return this.wasm.undo_depth();
  }

  // ─── Sync ──────────────────────────────────────────────────────────────────

  /**
   * Batch pending operations and send over the WebSocket.
   * Debounced to one flush per animation frame (≈16ms).
   */
  private scheduleFlush(): void {
    if (this.pendingFlush !== null || !this.connected) return;
    this.pendingFlush = requestAnimationFrame(() => {
      this.pendingFlush = null;
      this.flush();
    });
  }

  /** Immediately flush pending operations to the WebSocket. */
  flush(): void {
    if (!this.connected) return;
    const update = this.wasm.encode_pending_update();
    if (update.length > 0) {
      this.ws.send(wrapMessage(MsgType.UPDATE, update));
    }
  }

  /** Request a delta sync from the server (send our state vector). */
  requestDeltaSync(): void {
    const sv = this.wasm.encode_state_vector();
    this.ws.send(wrapMessage(MsgType.STATE_VECTOR, sv));
  }

  // ─── GC ────────────────────────────────────────────────────────────────────

  /** Update the Minimum Version Vector and optionally run GC. */
  updateMinVersion(mvvBytes: Uint8Array): GcStats | null {
    const result = this.wasm.update_min_version_and_gc(mvvBytes);
    if (result === null) return null;
    try {
      return JSON.parse(result as string) as GcStats;
    } catch {
      return null;
    }
  }

  // ─── Stats / Debug ─────────────────────────────────────────────────────────

  stats(): DocumentStats {
    return JSON.parse(this.wasm.stats()) as DocumentStats;
  }

  actorId(): bigint {
    return BigInt(this.wasm.actor_id());
  }

  lamport(): bigint {
    return BigInt(this.wasm.lamport());
  }

  // ─── WebSocket ─────────────────────────────────────────────────────────────

  private connectWebSocket(url: string): void {
    this.ws = new WebSocket(url);
    this.ws.binaryType = 'arraybuffer';

    this.ws.onopen = () => {
      this.connected = true;
      // On connect, request a delta sync in case we missed ops.
      this.requestDeltaSync();
      this.onConnected?.();
    };

    this.ws.onclose = () => {
      this.connected = false;
      this.onDisconnected?.();
    };

    this.ws.onerror = () => {
      this.connected = false;
    };

    this.ws.onmessage = (event: MessageEvent<ArrayBuffer>) => {
      this.handleMessage(new Uint8Array(event.data));
    };
  }

  private handleMessage(msg: Uint8Array): void {
    if (msg.length === 0) return;
    const type_ = msg[0] as MsgType;
    const payload = msg.subarray(1);

    switch (type_) {
      case MsgType.UPDATE: {
        const changedBuf = this.wasm.apply_update(payload);
        const changed = parseStrokeIds(changedBuf);
        if (changed.length > 0) {
          this.onStrokesChanged?.(changed);
        }
        break;
      }
      case MsgType.SNAPSHOT: {
        // Full state sync — replace local state.
        const newDoc = WasmDocument.from_snapshot(this.wasm.actor_id(), payload);
        this.wasm.free?.();
        this.wasm = newDoc;
        // Notify that everything changed.
        this.onStrokesChanged?.(this.getVisibleStrokeIds());
        break;
      }
      case MsgType.MVV: {
        const gcStats = this.updateMinVersion(payload);
        if (gcStats && gcStats.removed > 0) {
          console.debug('[vectis-crdt] GC:', gcStats);
        }
        break;
      }
      default:
        console.warn('[vectis-crdt] Unknown message type:', type_);
    }
  }

  /** Clean up resources. */
  destroy(): void {
    if (this.pendingFlush !== null) {
      cancelAnimationFrame(this.pendingFlush);
      this.pendingFlush = null;
    }
    this.ws.close();
    this.wasm.free?.();
  }
}
